In [5]:
# Importing the Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB

In [7]:
# Loading the Dataset
data = pd.read_csv('Spam Comments Detection.csv')

In [9]:
# Analyse the Top 5 rows of the Data
data.head()

,COMMENT_ID,AUTHOR,DATE,CONTENT,CLASS
0,LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU,Julius NM,2013-11-07T06:20:48,"Huh, anyway check out this you[tube] channel: ...",1
1,LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A,adam riyati,2013-11-07T12:37:15,Hey guys check out my new channel and our firs...,1
2,LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8,Evgeny Murashkin,2013-11-08T17:34:21,just for test I have to say murdev.com,1
3,z13jhp0bxqncu512g22wvzkasxmvvzjaz04,ElNino Melendez,2013-11-09T08:28:43,me shaking my sexy ass on my channel enjoy ^_^ ﻿,1
4,z13fwbwp1oujthgqj04chlngpvzmtt3r3dw,GsMega,2013-11-10T16:05:38,watch?v=vtaRGgvGtWQ Check this out .﻿,1

In [13]:
# We only need the content and class column from the dataset for the rest of the task. So let’s select both the columns
data = data[['CONTENT', 'CLASS']]

##### The class column contains values 0 and 1. 0 indicates not spam, and 1 indicates spam.

In [18]:
#  So to make it look better, I will use spam and not spam labels instead of 1 and 0\
data['CLASS'] = data['CLASS'].map({0 : 'Not Spam', 1: 'Spam'})

In [20]:
data.head()

                                             CONTENT CLASS
0  Huh, anyway check out this you[tube] channel: ...  Spam
1  Hey guys check out my new channel and our firs...  Spam
2             just for test I have to say murdev.com  Spam
3   me shaking my sexy ass on my channel enjoy ^_^ ﻿  Spam
4            watch?v=vtaRGgvGtWQ   Check this out .﻿  Spam

#### Training a Classification Model

##### As this problem is a problem of binary classification, We will use the Bernoulli Naive Bayes algorithm to train the model

In [31]:
x = np.array(data["CONTENT"])
y = np.array(data["CLASS"])

In [33]:
cv = CountVectorizer()
x = cv.fit_transform(x)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                test_size=0.2, 
                                                random_state=42)

In [35]:
model = BernoulliNB()
model.fit(xtrain, ytrain)

BernoulliNB()

In [37]:
model.score(xtest, ytest)

0.9857142857142858

In [39]:
# Now let’s test the model by giving spam and not spam comments as input
sample = 'https://github.com/kamran-ansari56?tab=overview&from=2025-04-01&to=2025-04-25'
data = cv.transform([sample]).toarray()
print(model.predict(data))

['Spam']

In [41]:
sample = "Lack of information!" 
data = cv.transform([sample]).toarray()
print(model.predict(data))

['Not Spam']

#### Summary

Spam comments detection means classifying comments as spam or not spam. Spam comments on social media platforms are the type of comments posted to redirect the user to another social media account, website or any piece of content.