In [1]:
# Importing the Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
!pip install torch

Requirement already satisfied: torch in c:\users\irt\anaconda3\lib\site-packages (2.7.1)
Requirement already satisfied: filelock in c:\users\irt\anaconda3\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\irt\anaconda3\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\irt\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in c:\users\irt\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\irt\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\irt\anaconda3\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: setuptools in c:\users\irt\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\irt\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\irt\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)

In [4]:
!pip install jovian

Collecting jovian
  Downloading jovian-0.2.47-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: requests in c:\users\irt\anaconda3\lib\site-packages (from jovian) (2.32.3)
Collecting uuid (from jovian)
  Downloading uuid-1.30.tar.gz (5.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pyyaml in c:\users\irt\anaconda3\lib\site-packages (from jovian) (6.0.2)
Requirement already satisfied: click in c:\users\irt\anaconda3\lib\site-packages (from jovian) (8.1.8)
Requirement already satisfied: colorama in c:\users\irt\anaconda3\lib\site-packages (from click->jovian) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\irt\anaconda3\lib\site-packages (from requests->jovian) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\irt\anaconda3\lib\site-packages (from requests->jovian) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\irt\anaconda3\lib\site-packages (from requests->jovian) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\irt\anaconda3\lib\site-packages (from requests->jovian) (2025.4.26)
Downloading jovian-0.2.47-py2.py3-none-any.whl (68 kB)
Building wheels for collected packages: uuid
  Building wheel for uuid (setup.py): started
  Building wheel for uuid (setup.py): finished with status 'done'
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6485 sha256=9b7e1ad3c8057c6dd7944201bdfa02e53450e8319f5fd305fa0822dbbc493ad7
  Stored in directory: c:\users\irt\appdata\local\pip\cache\wheels\cc\9d\72\13ff6a181eacfdbd6651ed761a4ee7c5c9f92034a9dc8a1b3c
Successfully built uuid
Installing collected packages: uuid, jovian

   ---------------------------------------- 2/2 [jovian]

Successfully installed jovian-0.2.47 uuid-1.30

  DEPRECATION: Building 'uuid' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'uuid'. Discussion can be found at https://github.com/pypa/pip/issues/6334

In [6]:
import torch
import jovian
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, random_split

In [7]:
# Loading the Data
data = pd.read_csv('car data.csv')

In [8]:
# Analyse the Top 5 rows of the Data
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [9]:
name = "Kamran Ansari"
def customize_dataset(data, rand_str):
    data = data.copy(deep = True)
    data =  data.sample(int(0.95*len(data)), random_state = int(ord(rand_str[0])))
    data.Year = data.Year * ord(rand_str[1]) / 100
    data.Selling_Price = data.Selling_Price * ord(rand_str[2]) / 100
    if ord(rand_str[3]) % 2 == 1:
        data = data.drop(['Car_Name'], axis = 1)
    return data

In [10]:
data = customize_dataset(data, name)
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
132,Bajaj Avenger 220,1956.49,0.8175,0.95,3500,Petrol,Individual,Manual,0
280,brio,1954.55,5.7225,5.90,14465,Petrol,Dealer,Manual,0
286,jazz,1955.52,6.1585,7.90,28569,Petrol,Dealer,Manual,0
61,etios cross,1954.55,4.9050,7.70,40588,Petrol,Dealer,Manual,0
242,xcent,1953.58,4.7960,7.13,34000,Petrol,Dealer,Manual,0

In [11]:
input_cols = ["Year","Present_Price","Kms_Driven","Owner"]
categorical_cols = ["Fuel_Type","Seller_Type","Transmission"]
output_cols = ["Selling_Price"]

#### Data Preparation

In [12]:

def dataframe_to_arrays(data):
    # Make a copy of the original dataframe
    dataframe1 = data.copy(deep=True)
    # Convert non-numeric categorical columns to numbers
    for col in categorical_cols:
        dataframe1[col] = dataframe1[col].astype('category').cat.codes
    # Extract input & outupts as numpy arrays
    inputs_array = dataframe1[input_cols].to_numpy()
    targets_array = dataframe1[output_cols].to_numpy()
    return inputs_array, targets_array

inputs_array, targets_array = dataframe_to_arrays(data)
inputs_array, targets_array

(array([[1.95649e+03, 9.50000e-01, 3.50000e+03, 0.00000e+00],
        [1.95455e+03, 5.90000e+00, 1.44650e+04, 0.00000e+00],
        [1.95552e+03, 7.90000e+00, 2.85690e+04, 0.00000e+00],
        ...,
        [1.95358e+03, 8.93000e+00, 8.30000e+04, 0.00000e+00],
        [1.95552e+03, 1.50000e+00, 1.80000e+04, 0.00000e+00],
        [1.95358e+03, 5.59000e+00, 2.70000e+04, 0.00000e+00]]),
 array([[ 0.8175],
        [ 5.7225],
        [ 6.1585],
        [ 4.905 ],
        [ 4.796 ],
        [ 1.0355],
        [ 1.1445],
        [ 0.5668],
        [ 0.2725],
        [ 6.4855],
        [ 0.7085],
        [ 7.3575],
        [ 1.4715],
        [ 6.3765],
        [ 0.654 ],
        [ 5.995 ],
        [ 4.3055],
        [ 4.905 ],
        [ 2.1255],
        [ 5.232 ],
        [ 5.6135],
        [ 0.4578],
        [ 3.379 ],
        [ 0.5232],
        [ 2.8885],
        [ 8.175 ],
        [ 5.0685],
        [ 5.995 ],
        [ 0.981 ],
        [21.5275],
        [ 0.109 ],
        [ 4.905 ],
        [ 0.654 ],
        [ 3.379 ],
        [12.2625],
        [ 0.436 ],
        [ 7.9025],
        [ 3.924 ],
        [ 1.2535],
        [ 0.218 ],
        [ 1.9075],
        [ 0.1962],
        [ 0.8175],
        [ 0.545 ],
        [17.44  ],
        [ 3.815 ],
        [ 0.4905],
        [ 3.161 ],
        [ 4.7415],
        [ 6.3765],
        [ 2.1255],
        [20.4375],
        [ 2.725 ],
        [ 0.436 ],
        [ 0.4905],
        [ 4.36  ],
        [ 0.3379],
        [ 2.9975],
        [ 1.1445],
        [11.1725],
        [ 0.218 ],
        [ 9.1015],
        [ 5.7225],
        [ 1.1445],
        [ 0.218 ],
        [ 0.545 ],
        [ 0.3815],
        [ 6.4855],
        [ 4.905 ],
        [ 6.8125],
        [ 6.8125],
        [ 4.36  ],
        [25.07  ],
        [ 5.232 ],
        [16.0557],
        [ 0.654 ],
        [ 3.4335],
        [ 9.7991],
        [ 0.654 ],
        [ 9.5375],
        [ 3.5425],
        [ 5.8315],
        [ 0.1635],
        [ 5.668 ],
        [ 0.3815],
        [ 1.1445],
        [ 5.45  ],
        [ 2.8885],
        [ 9.919 ],
        [ 1.3625],
        [ 0.218 ],
        [ 6.976 ],
        [ 3.8259],
        [ 9.4285],
        [ 5.341 ],
        [ 1.308 ],
        [ 2.9975],
        [ 4.796 ],
        [ 0.654 ],
        [ 4.3055],
        [ 3.161 ],
        [ 0.5995],
        [ 6.54  ],
        [ 0.8175],
        [ 0.436 ],
        [ 5.777 ],
        [ 3.5425],
        [ 0.4905],
        [ 8.1205],
        [ 5.7225],
        [ 2.4525],
        [11.881 ],
        [ 5.7225],
        [ 3.379 ],
        [ 3.7605],
        [ 0.4142],
        [ 0.654 ],
        [ 4.796 ],
        [ 2.943 ],
        [11.0199],
        [ 3.1065],
        [ 7.6845],
        [ 6.7035],
        [ 0.1744],
        [ 5.014 ],
        [ 3.815 ],
        [ 7.085 ],
        [ 0.4142],
        [ 0.7085],
        [ 9.3195],
        [ 6.54  ],
        [ 9.9735],
        [ 8.4475],
        [ 3.2155],
        [ 1.2535],
        [ 5.886 ],
        [ 2.4525],
        [12.8075],
        [ 3.5425],
        [ 0.218 ],
        [ 8.611 ],
        [ 8.1205],
        [15.805 ],
        [ 2.5615],
        [ 5.3955],
        [ 5.7225],
        [ 8.9925],
        [ 0.654 ],
        [ 0.3815],
        [ 4.905 ],
        [ 2.4525],
        [ 0.5232],
        [ 9.156 ],
        [ 0.7848],
        [ 0.5232],
        [ 0.327 ],
        [16.241 ],
        [12.2625],
        [ 0.2725],
        [ 0.436 ],
        [ 0.4905],
        [25.07  ],
        [ 2.725 ],
        [ 4.251 ],
        [ 3.27  ],
        [ 0.436 ],
        [ 5.1775],
        [ 5.1775],
        [10.0825],
        [ 0.7085],
        [10.0825],
        [ 6.54  ],
        [ 1.199 ],
        [ 0.5232],
        [ 0.2725],
        [22.6175],
        [12.4805],
        [35.97  ],
        [ 1.853 ],
        [ 3.161 ],
        [ 0.545 ],
        [ 2.7795],
        [38.15  ],
        [ 3.2155],
        [ 1.3625],
        [ 1.199 ],
        [25.615 ],
        [ 0.981 ],
        [ 0.8502],
        [ 0.2725],
        [ 0.654 ],
        [ 1.2535],
        [ 4.36  ],
        [ 5.777 ],
        [ 7.085 ],
        [ 4.469 ],
        [13.625 ],
        [ 0.327 ],
        [ 3.379 ],
        [12.535 ],
        [ 5.7225],
        [ 0.218 ],
        [ 0.872 ],
        [ 5.1775],
        [ 0.4578],
        [ 5.2865],
        [19.62  ],
        [ 8.4475],
        [25.07  ],
        [ 7.194 ],
        [ 8.1205],
        [ 6.2675],
        [ 5.1775],
        [ 0.4905],
        [ 3.6515],
        [18.53  ],
        [ 5.995 ],
        [10.355 ],
        [ 6.649 ],
        [21.7891],
        [ 3.9785],
        [ 4.251 ],
        [ 9.156 ],
        [ 6.322 ],
        [ 5.995 ],
        [10.0825],
        [ 1.2535],
        [ 4.36  ],
        [ 3.8041],
        [14.061 ],
        [ 5.886 ],
        [ 8.175 ],
        [ 2.7795],
        [ 0.5559],
        [ 1.635 ],
        [ 0.5995],
        [ 0.4905],
        [ 1.09  ],
        [ 0.1853],
        [ 7.848 ],
        [ 7.303 ],
        [ 3.1065],
        [ 8.066 ],
        [ 0.327 ],
        [ 4.142 ],
        [ 7.0305],
        [10.5185],
        [ 8.4475],
        [ 4.905 ],
        [ 4.0875],
        [ 0.4905],
        [10.573 ],
        [ 1.199 ],
        [ 4.0875],
        [ 7.4665],
        [ 1.308 ],
        [ 6.2675],
        [ 9.265 ],
        [ 0.2943],
        [ 0.8175],
        [ 5.7225],
        [ 4.905 ],
        [15.5325],
        [ 1.5805],
        [ 6.431 ],
        [ 1.4715],
        [ 5.1775],
        [ 1.7985],
        [ 0.4905],
        [ 1.4715],
        [ 0.545 ],
        [ 1.1445],
        [ 2.18  ],
        [ 2.289 ],
        [ 7.9025],
        [ 0.545 ],
        [ 8.9925],
        [ 3.1065],
        [ 3.27  ],
        [ 4.469 ],
        [ 0.2725],
        [ 5.1775],
        [ 5.341 ],
        [ 1.308 ],
        [ 3.6515]]))

In [13]:

inputs = torch.Tensor(inputs_array)
targets = torch.Tensor(targets_array)

dataset = TensorDataset(inputs, targets)
train_ds, val_ds = random_split(dataset, [228, 57])
batch_size = 128

train_loader = DataLoader(train_ds, batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size)

#### Creating PyTorch Model

In [14]:
input_size = len(input_cols)
output_size = len(output_cols)

class CarsModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)                  # fill this (hint: use input_size & output_size defined above)
        
    def forward(self, xb):
        out = self.linear(xb)                          # fill this
        return out
    
    def training_step(self, batch):
        inputs, targets = batch 
        # Generate predictions
        out = self(inputs)          
        # Calcuate loss
        loss = F.l1_loss(out, targets)                         # fill this
        return loss
    
    def validation_step(self, batch):
        inputs, targets = batch
        # Generate predictions
        out = self(inputs)
        # Calculate loss
        loss = F.l1_loss(out, targets)                           # fill this    
        return {'val_loss': loss.detach()}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        return {'val_loss': epoch_loss.item()}
    
    def epoch_end(self, epoch, result, num_epochs):
        # Print result every 20th epoch
        if (epoch+1) % 20 == 0 or epoch == num_epochs-1:
            print("Epoch [{}], val_loss: {:.4f}".format(epoch+1, result['val_loss']))
            
model = CarsModel()

list(model.parameters())

[Parameter containing:
 tensor([[-0.4061, -0.1524,  0.3326,  0.0024]], requires_grad=True),
 Parameter containing:
 tensor([-0.4333], requires_grad=True)]

#### Training Model to Predict Car Prices

In [15]:
# Eval algorithm
def evaluate(model, val_loader):
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

# Fitting algorithm
def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result, epochs)
        history.append(result)
    return history

# Check the initial value that val_loss have
result = evaluate(model, val_loader)
print(result)

{'val_loss': 14027.1767578125}

In [16]:

# Start with the Fitting
epochs = 90
lr = 1e-8
history1 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 13413.7344
Epoch [40], val_loss: 12801.2695
Epoch [60], val_loss: 12187.7227
Epoch [80], val_loss: 11573.9033
Epoch [90], val_loss: 11268.3770

In [17]:
# Train repeatdly until have a 'good' val_loss
epochs = 20
lr = 1e-9
history1 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 11207.2168

#### Using the Model to Predict Car Prices

In [18]:
# Prediction Algorithm
def predict_single(input, target, model):
    inputs = input.unsqueeze(0)
    predictions = model(inputs)                # fill this
    prediction = predictions[0].detach()
    print("Input:", input)
    print("Target:", target)
    print("Prediction:", prediction)

# Testing the model with some samples
input, target = val_ds[0]
predict_single(input, target, model)

Input: tensor([1.9546e+03, 1.4790e+01, 4.3535e+04, 0.0000e+00])
Target: tensor([12.8075])
Prediction: tensor([10902.4258])

In [19]:

input, target = val_ds[10]
predict_single(input, target, model)

Input: tensor([1.9516e+03, 9.4000e+00, 3.6000e+04, 0.0000e+00])
Target: tensor([4.9050])
Prediction: tensor([8878.4746])