In [1]:
# Importing the Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sentiments = SentimentIntensityAnalyzer()

In [27]:
# Loading the Data
import pandas as pd

data = pd.read_csv('hotel_reviews.csv', encoding='utf-8', encoding_errors='ignore', 
                   on_bad_lines='skip', engine='python')

In [28]:
# Analyse the Top 5 rows of the Data
data.head()

                                                                                                     =] Hotel_Reviews.csv \˒7O7dE
ҲdnK
Wy*z&& $ѕ/_?
d.uga"3}{#}ۻuYc}V҅
?w;o^ykk.o.Cm{ڞP
>
zG                     ~lt'~<6Twv
蛕{tElL4oݹh>Xۛ
󮍽ks]ޅ.T6W˯_fWՋ+...                           莕]9
K΀U:^=Ҭ`.M7
Git<:]?
ܵ!
r%o&|ζlRMo!4
zl˕
vqέ<698
; ۘn9tBz0Uw\ NaN                                                                                              None
747&)'                                          e+um(؂5.xZ:@{{05\jx1#kXwq7tsǢC2Kn
a-K w                                               None
7mܑmylܨx&[(n6Z0TG>B=
s0gg'                   NaN                                                                                              None
qd1zBM!
*Zd"Izl                           vo
A⧽xūyr                                                                                       None

In [29]:
data.tail()

                                                                                               =] Hotel_Reviews.csv \˒7O7dE
ҲdnK
Wy*z&& $ѕ/_?
d.uga"3}{#}ۻuYc}V҅
S _faZg޴/jtM/%n
72dt՝{ku8z_D%ii%1            NaN                                                                                       None
(ODniJ*'p>"`mHGESS
eGzE\HsOVn5^F}ya/Y[@
~... NaN                                                                                       None
;CϥOqE{                                          NaN                                                                                       None
oC3Ӣ
MP*2?Q:ﶰ)_                                qoIb-NGAOd
=ŷiټhb6ZfD\t*Rʻ*zKWH$M1m                                               None
#!6p-%ޅXVyf7"
I}sH̟8{LmH'Ycz
۶YpL<)=... NaN                                                                                       None

In [33]:
ratings = data["Rating"].value_counts()
numbers = ratings.index
quantity = ratings.values

custom_colors = ["skyblue", "yellowgreen", 'tomato', "blue", "red"]
plt.figure(figsize=(5, 5))
plt.pie(quantity, labels=numbers, colors=custom_colors)
central_circle = plt.Circle((0, 0), 0.5, color='white')
fig = plt.gcf()
fig.gca().add_artist(central_circle)
plt.rc('font', size=12)
plt.title("Hotel Reviews Ratings", fontsize=20)
plt.show()

KeyError: 'Rating'