In [1]:
# To use this library, you need to run these three commands below in your command prompt
!pip install fastai
!pip install fastbook --upgrade
!pip install -Uqq fastbook

Collecting fastai
  Downloading fastai-2.8.2-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: pip in c:\users\irt\anaconda3\lib\site-packages (from fastai) (24.2)
Requirement already satisfied: packaging in c:\users\irt\anaconda3\lib\site-packages (from fastai) (24.1)
Collecting fastdownload<2,>=0.0.5 (from fastai)
  Downloading fastdownload-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Collecting fastcore<1.9,>=1.8.0 (from fastai)
  Downloading fastcore-1.8.2-py3-none-any.whl.metadata (3.7 kB)
Collecting fasttransform>=0.0.2 (from fastai)
  Downloading fasttransform-0.0.2-py3-none-any.whl.metadata (7.6 kB)
Collecting torchvision>=0.11 (from fastai)
  Downloading torchvision-0.22.0-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: matplotlib in c:\users\irt\anaconda3\lib\site-packages (from fastai) (3.10.1)
Requirement already satisfied: pandas in c:\users\irt\anaconda3\lib\site-packages (from fastai) (2.1.4)
Requirement already satisfied: requests in c:\users\irt\anaconda3\lib\site-packages (from fastai) (2.32.3)
Requirement already satisfied: pyyaml in c:\users\irt\anaconda3\lib\site-packages (from fastai) (6.0.1)
Collecting fastprogress>=0.2.4 (from fastai)
  Downloading fastprogress-1.0.3-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pillow>=9.0.0 in c:\users\irt\anaconda3\lib\site-packages (from fastai) (10.4.0)
Requirement already satisfied: scikit-learn in c:\users\irt\anaconda3\lib\site-packages (from fastai) (1.4.2)
Requirement already satisfied: scipy in c:\users\irt\anaconda3\lib\site-packages (from fastai) (1.11.4)
Requirement already satisfied: spacy<4 in c:\users\irt\anaconda3\lib\site-packages (from fastai) (3.8.3)
Collecting plum-dispatch (from fastai)
  Downloading plum_dispatch-2.5.7-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: cloudpickle in c:\users\irt\anaconda3\lib\site-packages (from fastai) (3.0.0)
Collecting torch<2.8,>=1.10 (from fastai)
  Downloading torch-2.7.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (8.3.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (2.5.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (4.66.5)
Requirement already satisfied: numpy>=1.19.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (1.26.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (3.1.4)
Requirement already satisfied: setuptools in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (75.1.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai) (3.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastai) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastai) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastai) (2025.1.31)
Requirement already satisfied: filelock in c:\users\irt\anaconda3\lib\site-packages (from torch<2.8,>=1.10->fastai) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\irt\anaconda3\lib\site-packages (from torch<2.8,>=1.10->fastai) (4.11.0)
Collecting sympy>=1.13.3 (from torch<2.8,>=1.10->fastai)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx in c:\users\irt\anaconda3\lib\site-packages (from torch<2.8,>=1.10->fastai) (3.3)
Requirement already satisfied: fsspec in c:\users\irt\anaconda3\lib\site-packages (from torch<2.8,>=1.10->fastai) (2024.6.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\irt\anaconda3\lib\site-packages (from pandas->fastai) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\irt\anaconda3\lib\site-packages (from pandas->fastai) (2023.3)
Collecting beartype>=0.16.2 (from plum-dispatch->fastai)
  Downloading beartype-0.21.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: rich>=10.0 in c:\users\irt\anaconda3\lib\site-packages (from plum-dispatch->fastai) (13.7.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\irt\anaconda3\lib\site-packages (from scikit-learn->fastai) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\irt\anaconda3\lib\site-packages (from scikit-learn->fastai) (3.5.0)
Requirement already satisfied: language-data>=1.2 in c:\users\irt\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy<4->fastai) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\irt\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4->fastai) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\irt\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4->fastai) (2.20.1)
Requirement already satisfied: six>=1.5 in c:\users\irt\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->fastai) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\irt\anaconda3\lib\site-packages (from rich>=10.0->plum-dispatch->fastai) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\irt\anaconda3\lib\site-packages (from rich>=10.0->plum-dispatch->fastai) (2.15.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\irt\anaconda3\lib\site-packages (from sympy>=1.13.3->torch<2.8,>=1.10->fastai) (1.3.0)
Requirement already satisfied: blis<1.2.0,>=1.1.0 in c:\users\irt\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.0->spacy<4->fastai) (1.1.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\irt\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.0->spacy<4->fastai) (0.1.5)
Requirement already satisfied: colorama in c:\users\irt\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy<4->fastai) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\irt\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\irt\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (1.5.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\irt\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\irt\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\irt\anaconda3\lib\site-packages (from jinja2->spacy<4->fastai) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\irt\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<4->fastai) (1.2.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\irt\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.0->plum-dispatch->fastai) (0.1.0)
Downloading fastai-2.8.2-py3-none-any.whl (235 kB)
Downloading fastcore-1.8.2-py3-none-any.whl (78 kB)
Downloading fastdownload-0.0.7-py3-none-any.whl (12 kB)
Downloading fastprogress-1.0.3-py3-none-any.whl (12 kB)
Downloading fasttransform-0.0.2-py3-none-any.whl (14 kB)
Downloading torch-2.7.0-cp312-cp312-win_amd64.whl (212.5 MB)
   ---------------------------------------- 0.0/212.5 MB ? eta -:--:--
   ---------------------------------------- 0.8/212.5 MB 3.7 MB/s eta 0:00:57
   ---------------------------------------- 1.6/212.5 MB 3.8 MB/s eta 0:00:56
   ---------------------------------------- 2.6/212.5 MB 4.2 MB/s eta 0:00:50
    --------------------------------------- 3.7/212.5 MB 4.6 MB/s eta 0:00:45
    --------------------------------------- 4.7/212.5 MB 4.7 MB/s eta 0:00:45
   - -------------------------------------- 5.8/212.5 MB 4.7 MB/s eta 0:00:45
   - -------------------------------------- 6.8/212.5 MB 4.8 MB/s eta 0:00:44
   - -------------------------------------- 8.4/212.5 MB 5.0 MB/s eta 0:00:41
   - -------------------------------------- 10.0/212.5 MB 5.3 MB/s eta 0:00:39
   -- ------------------------------------- 11.3/212.5 MB 5.5 MB/s eta 0:00:37
   -- ------------------------------------- 13.1/212.5 MB 5.7 MB/s eta 0:00:36
   -- ------------------------------------- 14.2/212.5 MB 5.7 MB/s eta 0:00:35
   -- ------------------------------------- 15.5/212.5 MB 5.7 MB/s eta 0:00:35
   --- ------------------------------------ 16.5/212.5 MB 5.7 MB/s eta 0:00:35
   --- ------------------------------------ 17.8/212.5 MB 5.7 MB/s eta 0:00:35
   --- ------------------------------------ 19.1/212.5 MB 5.7 MB/s eta 0:00:34
   --- ------------------------------------ 20.4/212.5 MB 5.8 MB/s eta 0:00:34
   ---- ----------------------------------- 21.8/212.5 MB 5.8 MB/s eta 0:00:33
   ---- ----------------------------------- 22.8/212.5 MB 5.8 MB/s eta 0:00:33
   ---- ----------------------------------- 23.9/212.5 MB 5.8 MB/s eta 0:00:33
   ---- ----------------------------------- 25.2/212.5 MB 5.7 MB/s eta 0:00:33
   ---- ----------------------------------- 26.2/212.5 MB 5.7 MB/s eta 0:00:33
   ----- ---------------------------------- 27.0/212.5 MB 5.6 MB/s eta 0:00:33
   ----- ---------------------------------- 28.0/212.5 MB 5.6 MB/s eta 0:00:33
   ----- ---------------------------------- 29.1/212.5 MB 5.5 MB/s eta 0:00:34
   ----- ---------------------------------- 29.9/212.5 MB 5.5 MB/s eta 0:00:34
   ----- ---------------------------------- 30.9/212.5 MB 5.5 MB/s eta 0:00:34
   ----- ---------------------------------- 31.7/212.5 MB 5.4 MB/s eta 0:00:34
   ------ --------------------------------- 32.2/212.5 MB 5.3 MB/s eta 0:00:34
   ------ --------------------------------- 33.0/212.5 MB 5.3 MB/s eta 0:00:34
   ------ --------------------------------- 33.8/212.5 MB 5.2 MB/s eta 0:00:35
   ------ --------------------------------- 34.9/212.5 MB 5.2 MB/s eta 0:00:35
   ------ --------------------------------- 35.9/212.5 MB 5.2 MB/s eta 0:00:34
   ------- -------------------------------- 37.2/212.5 MB 5.2 MB/s eta 0:00:34
   ------- -------------------------------- 38.0/212.5 MB 5.2 MB/s eta 0:00:34
   ------- -------------------------------- 39.3/212.5 MB 5.2 MB/s eta 0:00:34
   ------- -------------------------------- 40.4/212.5 MB 5.2 MB/s eta 0:00:33
   ------- -------------------------------- 41.2/212.5 MB 5.2 MB/s eta 0:00:34
   ------- -------------------------------- 41.7/212.5 MB 5.1 MB/s eta 0:00:34
   -------- ------------------------------- 42.7/212.5 MB 5.1 MB/s eta 0:00:34
   -------- ------------------------------- 43.5/212.5 MB 5.1 MB/s eta 0:00:34
   -------- ------------------------------- 44.3/212.5 MB 5.0 MB/s eta 0:00:34
   -------- ------------------------------- 45.4/212.5 MB 5.0 MB/s eta 0:00:34
   -------- ------------------------------- 46.4/212.5 MB 5.0 MB/s eta 0:00:33
   -------- ------------------------------- 47.2/212.5 MB 5.0 MB/s eta 0:00:34
   --------- ------------------------------ 48.2/212.5 MB 5.0 MB/s eta 0:00:33
   --------- ------------------------------ 49.3/212.5 MB 5.0 MB/s eta 0:00:33
   --------- ------------------------------ 50.6/212.5 MB 5.0 MB/s eta 0:00:33
   --------- ------------------------------ 51.6/212.5 MB 5.0 MB/s eta 0:00:32
   --------- ------------------------------ 52.7/212.5 MB 5.0 MB/s eta 0:00:32
   ---------- ----------------------------- 53.2/212.5 MB 5.0 MB/s eta 0:00:32
   ---------- ----------------------------- 53.7/212.5 MB 4.9 MB/s eta 0:00:33
   ---------- ----------------------------- 54.8/212.5 MB 4.9 MB/s eta 0:00:32
   ---------- ----------------------------- 56.1/212.5 MB 4.9 MB/s eta 0:00:32
   ---------- ----------------------------- 56.9/212.5 MB 5.0 MB/s eta 0:00:32
   ---------- ----------------------------- 57.9/212.5 MB 4.9 MB/s eta 0:00:32
   ----------- ---------------------------- 58.5/212.5 MB 4.9 MB/s eta 0:00:32
   ----------- ---------------------------- 59.0/212.5 MB 4.9 MB/s eta 0:00:32
   ----------- ---------------------------- 59.8/212.5 MB 4.8 MB/s eta 0:00:32
   ----------- ---------------------------- 60.3/212.5 MB 4.8 MB/s eta 0:00:32
   ----------- ---------------------------- 60.8/212.5 MB 4.8 MB/s eta 0:00:32
   ----------- ---------------------------- 61.3/212.5 MB 4.7 MB/s eta 0:00:33
   ----------- ---------------------------- 61.9/212.5 MB 4.7 MB/s eta 0:00:33
   ----------- ---------------------------- 62.4/212.5 MB 4.6 MB/s eta 0:00:33
   ----------- ---------------------------- 62.7/212.5 MB 4.6 MB/s eta 0:00:33
   ----------- ---------------------------- 63.4/212.5 MB 4.6 MB/s eta 0:00:33
   ------------ --------------------------- 64.2/212.5 MB 4.6 MB/s eta 0:00:33
   ------------ --------------------------- 65.3/212.5 MB 4.6 MB/s eta 0:00:33
   ------------ --------------------------- 66.1/212.5 MB 4.6 MB/s eta 0:00:32
   ------------ --------------------------- 66.8/212.5 MB 4.6 MB/s eta 0:00:32
   ------------ --------------------------- 67.6/212.5 MB 4.5 MB/s eta 0:00:32
   ------------ --------------------------- 68.4/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 69.5/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 70.3/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 71.0/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 71.8/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 72.4/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 73.1/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 73.7/212.5 MB 4.5 MB/s eta 0:00:32
   ------------- -------------------------- 73.9/212.5 MB 4.4 MB/s eta 0:00:32
   ------------- -------------------------- 74.2/212.5 MB 4.4 MB/s eta 0:00:32
   -------------- ------------------------- 74.4/212.5 MB 4.3 MB/s eta 0:00:32
   -------------- ------------------------- 75.0/212.5 MB 4.3 MB/s eta 0:00:32
   -------------- ------------------------- 75.2/212.5 MB 4.3 MB/s eta 0:00:33
   -------------- ------------------------- 75.5/212.5 MB 4.3 MB/s eta 0:00:33
   -------------- ------------------------- 75.8/212.5 MB 4.2 MB/s eta 0:00:33
   -------------- ------------------------- 76.0/212.5 MB 4.2 MB/s eta 0:00:33
   -------------- ------------------------- 76.3/212.5 MB 4.2 MB/s eta 0:00:33
   -------------- ------------------------- 76.8/212.5 MB 4.1 MB/s eta 0:00:34
   -------------- ------------------------- 77.1/212.5 MB 4.1 MB/s eta 0:00:34
   -------------- ------------------------- 77.1/212.5 MB 4.1 MB/s eta 0:00:34
   -------------- ------------------------- 77.3/212.5 MB 4.0 MB/s eta 0:00:34
   -------------- ------------------------- 77.3/212.5 MB 4.0 MB/s eta 0:00:34
   -------------- ------------------------- 77.6/212.5 MB 4.0 MB/s eta 0:00:35
   -------------- ------------------------- 78.1/212.5 MB 3.9 MB/s eta 0:00:35
   -------------- ------------------------- 78.4/212.5 MB 3.9 MB/s eta 0:00:35
   -------------- ------------------------- 79.2/212.5 MB 3.9 MB/s eta 0:00:35
   --------------- ------------------------ 79.7/212.5 MB 3.9 MB/s eta 0:00:35
   --------------- ------------------------ 80.2/212.5 MB 3.9 MB/s eta 0:00:35
   --------------- ------------------------ 80.5/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 81.0/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 81.5/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 81.8/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 82.3/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 82.3/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 82.3/212.5 MB 3.8 MB/s eta 0:00:35
   --------------- ------------------------ 82.6/212.5 MB 3.7 MB/s eta 0:00:36
   --------------- ------------------------ 83.1/212.5 MB 3.7 MB/s eta 0:00:36
   --------------- ------------------------ 83.4/212.5 MB 3.6 MB/s eta 0:00:36
   --------------- ------------------------ 83.9/212.5 MB 3.6 MB/s eta 0:00:36
   --------------- ------------------------ 84.1/212.5 MB 3.6 MB/s eta 0:00:36
   --------------- ------------------------ 84.9/212.5 MB 3.6 MB/s eta 0:00:36
   ---------------- ----------------------- 85.5/212.5 MB 3.6 MB/s eta 0:00:36
   ---------------- ----------------------- 86.0/212.5 MB 3.6 MB/s eta 0:00:36
   ---------------- ----------------------- 86.5/212.5 MB 3.6 MB/s eta 0:00:36
   ---------------- ----------------------- 87.0/212.5 MB 3.6 MB/s eta 0:00:36
   ---------------- ----------------------- 87.6/212.5 MB 3.6 MB/s eta 0:00:36
   ---------------- ----------------------- 88.1/212.5 MB 3.5 MB/s eta 0:00:36
   ---------------- ----------------------- 88.6/212.5 MB 3.5 MB/s eta 0:00:36
   ---------------- ----------------------- 88.9/212.5 MB 3.5 MB/s eta 0:00:36
   ---------------- ----------------------- 89.7/212.5 MB 3.5 MB/s eta 0:00:35
   ---------------- ----------------------- 90.2/212.5 MB 3.5 MB/s eta 0:00:35
   ----------------- ---------------------- 90.4/212.5 MB 3.5 MB/s eta 0:00:35
   ----------------- ---------------------- 91.2/212.5 MB 3.5 MB/s eta 0:00:35
   ----------------- ---------------------- 92.3/212.5 MB 3.5 MB/s eta 0:00:35
   ----------------- ---------------------- 93.1/212.5 MB 3.5 MB/s eta 0:00:35
   ----------------- ---------------------- 93.6/212.5 MB 3.5 MB/s eta 0:00:34
   ----------------- ---------------------- 93.8/212.5 MB 3.5 MB/s eta 0:00:35

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\irt\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\irt\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\irt\anaconda3\Lib\site-packages)

Collecting fastbook
  Downloading fastbook-0.0.29-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pip in c:\users\irt\anaconda3\lib\site-packages (from fastbook) (24.2)
Requirement already satisfied: packaging in c:\users\irt\anaconda3\lib\site-packages (from fastbook) (24.1)
Requirement already satisfied: fastai>=2.6 in c:\users\irt\anaconda3\lib\site-packages (from fastbook) (2.8.2)
Collecting graphviz (from fastbook)
  Downloading graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas in c:\users\irt\anaconda3\lib\site-packages (from fastbook) (2.1.4)
Requirement already satisfied: requests in c:\users\irt\anaconda3\lib\site-packages (from fastbook) (2.32.3)
Collecting transformers (from fastbook)
  Downloading transformers-4.52.3-py3-none-any.whl.metadata (40 kB)
Collecting datasets (from fastbook)
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: ipywidgets<8 in c:\users\irt\anaconda3\lib\site-packages (from fastbook) (7.8.1)
Collecting sentencepiece (from fastbook)
  Downloading sentencepiece-0.2.0-cp312-cp312-win_amd64.whl.metadata (8.3 kB)
Requirement already satisfied: fastdownload<2,>=0.0.5 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (0.0.7)
Requirement already satisfied: fastcore<1.9,>=1.8.0 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (1.8.2)
Requirement already satisfied: fasttransform>=0.0.2 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (0.0.2)
Requirement already satisfied: torchvision>=0.11 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (0.22.0)
Requirement already satisfied: matplotlib in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (3.10.1)
Requirement already satisfied: pyyaml in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (6.0.1)
Requirement already satisfied: fastprogress>=0.2.4 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (1.0.3)
Requirement already satisfied: pillow>=9.0.0 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (10.4.0)
Requirement already satisfied: scikit-learn in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (1.4.2)
Requirement already satisfied: scipy in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (1.11.4)
Requirement already satisfied: spacy<4 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (3.8.3)
Requirement already satisfied: plum-dispatch in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (2.5.7)
Requirement already satisfied: cloudpickle in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (3.0.0)
Requirement already satisfied: torch<2.8,>=1.10 in c:\users\irt\anaconda3\lib\site-packages (from fastai>=2.6->fastbook) (2.7.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\irt\anaconda3\lib\site-packages (from ipywidgets<8->fastbook) (0.2.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\irt\anaconda3\lib\site-packages (from ipywidgets<8->fastbook) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\irt\anaconda3\lib\site-packages (from ipywidgets<8->fastbook) (5.14.3)
Requirement already satisfied: widgetsnbextension~=3.6.6 in c:\users\irt\anaconda3\lib\site-packages (from ipywidgets<8->fastbook) (3.6.6)
Requirement already satisfied: ipython>=4.0.0 in c:\users\irt\anaconda3\lib\site-packages (from ipywidgets<8->fastbook) (8.27.0)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in c:\users\irt\anaconda3\lib\site-packages (from ipywidgets<8->fastbook) (1.0.0)
Requirement already satisfied: filelock in c:\users\irt\anaconda3\lib\site-packages (from datasets->fastbook) (3.13.1)
Requirement already satisfied: numpy>=1.17 in c:\users\irt\anaconda3\lib\site-packages (from datasets->fastbook) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\irt\anaconda3\lib\site-packages (from datasets->fastbook) (16.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\irt\anaconda3\lib\site-packages (from datasets->fastbook) (0.3.8)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\irt\anaconda3\lib\site-packages (from datasets->fastbook) (4.66.5)
Requirement already satisfied: xxhash in c:\users\irt\anaconda3\lib\site-packages (from datasets->fastbook) (3.5.0)
Collecting multiprocess<0.70.17 (from datasets->fastbook)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\irt\anaconda3\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (2024.6.1)
Collecting huggingface-hub>=0.24.0 (from datasets->fastbook)
  Downloading huggingface_hub-0.32.2-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastbook) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastbook) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastbook) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\irt\anaconda3\lib\site-packages (from requests->fastbook) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\irt\anaconda3\lib\site-packages (from pandas->fastbook) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\irt\anaconda3\lib\site-packages (from pandas->fastbook) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\irt\anaconda3\lib\site-packages (from pandas->fastbook) (2023.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\irt\anaconda3\lib\site-packages (from transformers->fastbook) (2024.9.11)
Collecting tokenizers<0.22,>=0.21 (from transformers->fastbook)
  Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.3 (from transformers->fastbook)
  Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\irt\anaconda3\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (3.10.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\irt\anaconda3\lib\site-packages (from huggingface-hub>=0.24.0->datasets->fastbook) (4.11.0)
Requirement already satisfied: decorator in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (2.15.1)
Requirement already satisfied: stack-data in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (0.2.0)
Requirement already satisfied: colorama in c:\users\irt\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<8->fastbook) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\irt\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->fastbook) (1.16.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (8.3.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (2.5.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (0.15.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (3.1.4)
Requirement already satisfied: setuptools in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (75.1.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\irt\anaconda3\lib\site-packages (from spacy<4->fastai>=2.6->fastbook) (3.5.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\irt\anaconda3\lib\site-packages (from torch<2.8,>=1.10->fastai>=2.6->fastbook) (1.14.0)
Requirement already satisfied: networkx in c:\users\irt\anaconda3\lib\site-packages (from torch<2.8,>=1.10->fastai>=2.6->fastbook) (3.3)
Requirement already satisfied: notebook>=4.4.1 in c:\users\irt\anaconda3\lib\site-packages (from widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (7.3.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai>=2.6->fastbook) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai>=2.6->fastbook) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai>=2.6->fastbook) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai>=2.6->fastbook) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\irt\anaconda3\lib\site-packages (from matplotlib->fastai>=2.6->fastbook) (3.1.2)
Requirement already satisfied: beartype>=0.16.2 in c:\users\irt\anaconda3\lib\site-packages (from plum-dispatch->fastai>=2.6->fastbook) (0.21.0)
Requirement already satisfied: rich>=10.0 in c:\users\irt\anaconda3\lib\site-packages (from plum-dispatch->fastai>=2.6->fastbook) (13.7.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\irt\anaconda3\lib\site-packages (from scikit-learn->fastai>=2.6->fastbook) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\irt\anaconda3\lib\site-packages (from scikit-learn->fastai>=2.6->fastbook) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\irt\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\irt\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\irt\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\irt\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\irt\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\irt\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->fastbook) (1.11.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\irt\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets<8->fastbook) (0.8.3)
Requirement already satisfied: language-data>=1.2 in c:\users\irt\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy<4->fastai>=2.6->fastbook) (1.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\irt\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\irt\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (2.27.3)
Requirement already satisfied: jupyterlab<4.4,>=4.3.4 in c:\users\irt\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (4.3.4)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\irt\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (0.2.3)
Requirement already satisfied: tornado>=6.2.0 in c:\users\irt\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (6.4.1)
Requirement already satisfied: wcwidth in c:\users\irt\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets<8->fastbook) (0.2.5)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\irt\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4->fastai>=2.6->fastbook) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\irt\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4->fastai>=2.6->fastbook) (2.20.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\irt\anaconda3\lib\site-packages (from rich>=10.0->plum-dispatch->fastai>=2.6->fastbook) (2.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\irt\anaconda3\lib\site-packages (from sympy>=1.13.3->torch<2.8,>=1.10->fastai>=2.6->fastbook) (1.3.0)
Requirement already satisfied: blis<1.2.0,>=1.1.0 in c:\users\irt\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.0->spacy<4->fastai>=2.6->fastbook) (1.1.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\irt\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.0->spacy<4->fastai>=2.6->fastbook) (0.1.5)
Requirement already satisfied: click>=8.0.0 in c:\users\irt\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai>=2.6->fastbook) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\irt\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai>=2.6->fastbook) (1.5.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\irt\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai>=2.6->fastbook) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\irt\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai>=2.6->fastbook) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\irt\anaconda3\lib\site-packages (from jinja2->spacy<4->fastai>=2.6->fastbook) (2.1.3)
Requirement already satisfied: executing in c:\users\irt\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets<8->fastbook) (0.8.3)
Requirement already satisfied: asttokens in c:\users\irt\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets<8->fastbook) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\irt\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets<8->fastbook) (0.2.2)
Requirement already satisfied: anyio>=3.1.0 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (21.3.0)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (7.16.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (7.4.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (2.0.10)
Requirement already satisfied: pyzmq>=24 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (25.1.2)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\irt\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\irt\anaconda3\lib\site-packages (from jupyterlab<4.4,>=4.3.4->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\irt\anaconda3\lib\site-packages (from jupyterlab<4.4,>=4.3.4->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets<8->fastbook) (0.27.0)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\irt\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\irt\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\irt\anaconda3\Lib\site-packages)

In [5]:
import fastbook
fastbook.setup_book()

In [7]:
# Now let’s import the necessary libraries and the dataset that we need to work
from fastai.vision.all import *
path = untar_data(URLs.PETS)

##### In FastAI, untar_data is a very powerful convenience function to download files from a URL. We are using the PETS dataset here which includes 37 categories of pets with roughly around 200 images of each class.

In [10]:
def is_cat(x):
  return x[0].isupper()

In [12]:
# Now let's use the ImageDataLoader function which raps around several data loaders for the problems of computer vision

dls = ImageDataLoaders.from_name_func(
    path,
    get_image_files(path),
    valid_pct = 0.2,
    seed = 42,
    label_func = is_cat,
    item_tfms = Resize(224)
)

#### Final Step: Making Predictions

In [21]:
learn =vision_learner(dls,
                   resnet34,
                   metrics = error_rate)

learn.fine_tune(1)
import ipywidgets as widgets

uploader = widgets.FileUpload()
uploader
def pred():
  img = PILImage.create(uploader.data[0])
  img.show()

  #Make Prediction
  is_cat,_,probs = learn.predict(img)

  print(f"Image is of a Cat: {is_cat}.")
  print(f"Probability image is a cat: {probs[1].item():.6f}")
  pred()